version: '2'

services:

  db:
    restart: 'unless-stopped'
    image: 'mysql/mysql-server:5.7'
    env_file: '.env'
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'
  fcrepo:
    restart: 'unless-stopped'
    image: 'quay.io/upennlibraries/fcrepo_dev:latest'
    depends_on:
      - 'db'
    links:
      - 'db'
    ports:
     - '8080:8080'
    volumes:
      - '.:/fcrepo'
      - '${LOCAL_BACKUP}:${REMOTE_BACKUP}'
    env_file: '.env'

volumes:
  fcrepo:
  db:
