version: '2'

services:

  db:
    image: 'mysql/mysql-server:5.7'
    env_file: '.env'
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'
  fcrepo:
    image: 'fcrepo_dev:latest'
    depends_on:
      - 'db'
    links:
      - 'db'
    ports:
     - '8080:8080'
    volumes:
      - '.:/fcrepo'
    env_file: '.env'

volumes:
  fcrepo:
  db:




