version: '2'

services:

  fcrepo:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - '.:/fcrepo'
      - '${LOCAL_DISPLAY}:/colenda_dirs'
    env_file:
      - '.env'

volumes:
  fcrepo:




